import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { StorefrontTemplatePreview } from "@/components/StorefrontTemplatePreview";
import { StorefrontTemplateManager } from "@/components/StorefrontTemplateManager";
import { formatDate, formatMoney } from "@/lib/format";
import { canAccessAdmin } from "@/lib/roles";
import { trpc } from "@/lib/trpc";
import { STOREFRONT_TEMPLATES } from "@shared/storefrontTemplates";
import { Activity, BadgeDollarSign, Building2, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, CreditCard, FileText, LayoutDashboard, LayoutTemplate, Loader2, LogOut, ShieldAlert, ShieldCheck, Store, UsersRound, XCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

type Section = "overview" | "payments" | "plans" | "subscriptions" | "templates" | "audit";

export default function AdminPanel() {
  const { loading, user, logout } = useAuth();
  const [, setLocation] = useLocation();
  if (loading) return <div className="grid min-h-screen place-items-center"><Loader2 className="size-7 animate-spin text-primary"/></div>;
  if (!user) return <main className="grid min-h-screen place-items-center p-6"><Card className="w-full max-w-md"><CardContent className="p-9 text-center"><ShieldCheck className="mx-auto size-10 text-primary"/><h1 className="mt-4 text-xl font-extrabold">دخول إداري محمي</h1><p className="mt-2 text-sm leading-7 text-muted-foreground">سجّل الدخول أولاً للوصول إلى إدارة منصة ZAYROX.</p><Button className="mt-6" onClick={() => setLocation("/login")}>تسجيل الدخول</Button></CardContent></Card></main>;
  if (!canAccessAdmin(user.role)) return <main className="grid min-h-screen place-items-center p-6"><Card className="w-full max-w-md border-rose-200"><CardContent className="p-9 text-center"><ShieldAlert className="mx-auto size-10 text-rose-600"/><h1 className="mt-4 text-xl font-extrabold">لا تملك صلاحية الإدارة</h1><p className="mt-2 text-sm leading-7 text-muted-foreground">هذه المساحة مخصصة لمالك المنصة فقط. يمكنك العودة لإدارة محلك من الزر التالي.</p><Button className="mt-6" onClick={() => setLocation("/dashboard")}>العودة إلى محلي</Button></CardContent></Card></main>;
  return <AdminWorkspace name={user.name ?? "Super Admin"} onLogout={logout}/>;
}

function AdminWorkspace({ name, onLogout }: { name: string; onLogout: () => void }) {
  const [section, setSection] = useState<Section>("overview");
  const [, setLocation] = useLocation();
  const utils = trpc.useUtils();
  const metrics = trpc.billingAdmin.metrics.useQuery();
  const payments = trpc.billingAdmin.paymentRequests.useQuery({});
  const plans = trpc.billingAdmin.plans.useQuery();
  const subscriptions = trpc.billingAdmin.subscriptions.useQuery();
  const audit = trpc.billingAdmin.auditLogs.useQuery();
  const storefronts = trpc.storefrontAdmin.shops.useQuery();
  const review = trpc.billingAdmin.review.useMutation({ onSuccess: () => { toast.success("تم حفظ قرار المراجعة وتحديث الاشتراك"); utils.billingAdmin.invalidate(); }, onError: error => toast.error(error.message) });
  const updatePlan = trpc.billingAdmin.updatePlan.useMutation({ onSuccess: () => { toast.success("تم حفظ إعدادات الباقة"); utils.billingAdmin.invalidate(); }, onError: error => toast.error(error.message) });
  const changeStatus = trpc.billingAdmin.setSubscriptionStatus.useMutation({ onSuccess: () => { toast.success("تم تحديث حالة الاشتراك"); utils.billingAdmin.invalidate(); }, onError: error => toast.error(error.message) });
  const updateTemplate = trpc.storefrontAdmin.setTemplate.useMutation({ onSuccess: () => { toast.success("تم تعيين قالب المتجر وتسجيل التغيير"); utils.storefrontAdmin.shops.invalidate(); utils.billingAdmin.auditLogs.invalidate(); }, onError: error => toast.error(error.message) });
  const nav: { id: Section; label: string; icon: any }[] = [
    { id: "overview", label: "نظرة المنصة", icon: LayoutDashboard }, { id: "payments", label: "طلبات الدفع", icon: CreditCard }, { id: "plans", label: "الباقات والأسعار", icon: BadgeDollarSign }, { id: "subscriptions", label: "الاشتراكات", icon: Building2 }, { id: "templates", label: "قوالب المتاجر", icon: LayoutTemplate }, { id: "audit", label: "سجل العمليات", icon: Activity },
  ];
  return <div className="min-h-screen bg-[#f8faf9] text-foreground" dir="rtl"><header className="border-b bg-white"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between gap-4 px-4 py-3 md:px-8"><button onClick={() => setLocation("/admin")} className="flex items-center gap-3 text-right"><span className="grid size-10 place-items-center rounded-xl bg-slate-900 text-white"><ShieldCheck className="size-5"/></span><span><b className="block text-sm">ZAYROX CONTROL</b><small className="text-[10px] text-muted-foreground">SUPER ADMIN</small></span></button><div className="flex items-center gap-2"><span className="hidden rounded-full bg-slate-100 px-3 py-2 text-xs font-bold text-slate-700 sm:block">{name}</span><Button size="sm" variant="outline" onClick={() => setLocation("/dashboard")}><Store className="ml-1 size-4"/>المتاجر</Button><Button size="sm" variant="ghost" onClick={onLogout}><LogOut className="size-4"/></Button></div></div></header><main className="mx-auto grid max-w-7xl gap-6 px-4 py-6 lg:grid-cols-[220px_1fr] lg:px-8"><aside className="h-fit rounded-2xl border bg-white p-2"><nav className="grid gap-1">{nav.map(item => <button key={item.id} onClick={() => setSection(item.id)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-right text-sm transition ${section === item.id ? "bg-slate-900 font-bold text-white" : "text-slate-600 hover:bg-slate-100"}`}><item.icon className="size-4"/>{item.label}</button>)}</nav></aside><section className="min-w-0">{section === "overview" && <Overview metrics={metrics.data}/>} {section === "payments" && <Payments rows={payments.data ?? []} pending={review.isPending} onReview={(paymentRequestId, decision, rejectionReason) => review.mutate({ paymentRequestId, decision, rejectionReason })}/>} {section === "plans" && <Plans plans={plans.data ?? []} pending={updatePlan.isPending} onSave={value => updatePlan.mutate(value)}/>} {section === "subscriptions" && <Subscriptions rows={subscriptions.data ?? []} pending={changeStatus.isPending} onChange={(shopId, status) => changeStatus.mutate({ shopId, status })}/>} {section === "templates" && <StorefrontTemplateManager rows={storefronts.data ?? []} pending={updateTemplate.isPending} onCommit={(shopId, storefrontTemplate) => updateTemplate.mutate({ shopId, storefrontTemplate })}/>} {section === "audit" && <Audit rows={audit.data ?? []}/>}</section></main></div>;
}

function Overview({ metrics }: { metrics: any }) { return <div className="space-y-6"><Header title="لوحة Super Admin" text="ملخص مباشر للمستخدمين والمتاجر والاشتراكات والمدفوعات."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={UsersRound} label="إجمالي المستخدمين" value={String(metrics?.totalUsers ?? 0)} tone="teal"/><Metric icon={Building2} label="إجمالي المتاجر" value={String(metrics?.totalShops ?? 0)} tone="slate"/><Metric icon={CheckCircle2} label="اشتراكات نشطة" value={String(metrics?.activeSubscriptions ?? 0)} tone="gold"/><Metric icon={Clock3} label="طلبات معلقة" value={String(metrics?.pendingRequests ?? 0)} tone="rose"/></div><Card><CardHeader><CardTitle>الإيرادات المعتمدة</CardTitle></CardHeader><CardContent><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-primary/10 text-primary"><CircleDollarSign/></span><div><b className="text-2xl">{formatMoney(metrics?.approvedRevenueCents ?? 0, "EGP")}</b><p className="mt-1 text-xs text-muted-foreground">إجمالي الطلبات التي اعتُمدت يدوياً عبر Vodafone Cash.</p></div></div></CardContent></Card></div>; }
function Payments({ rows, pending, onReview }: { rows: any[]; pending: boolean; onReview: (id: number, decision: "approved" | "rejected", reason?: string) => void }) { return <div className="space-y-5"><Header title="مراجعة المدفوعات" text="لا يُفعّل أي اشتراك قبل مراجعة الإيصال واتخاذ قرار واضح."/><Card><CardContent className="p-0">{rows.length ? <div className="divide-y">{rows.map(row => <div key={row.request.id} className="flex flex-wrap items-center gap-4 p-5"><div className="min-w-[190px] flex-1"><b className="block text-sm">{row.shopName}</b><p className="mt-1 text-xs text-muted-foreground">{row.userName ?? row.userEmail ?? "صاحب المحل"} · {row.request.orderCode}</p><p className="mt-1 text-xs text-muted-foreground">باقة {row.request.plan === "basic" ? "أساسية" : "احترافية"} · {statusLabel(row.request.status)}</p></div><b className="text-sm">{formatMoney(row.request.amountCents, "EGP")}</b><a href={row.request.receiptUrl} target="_blank" rel="noreferrer" className="rounded-lg border px-3 py-2 text-xs font-bold text-primary">عرض الإيصال</a>{row.request.status === "pending" && <div className="flex gap-2"><Button size="sm" disabled={pending} onClick={() => onReview(row.request.id, "approved")}><CheckCircle2 className="ml-1 size-4"/>قبول</Button><Button size="sm" variant="outline" disabled={pending} onClick={() => { const reason = window.prompt("سبب رفض التحويل"); if (reason?.trim()) onReview(row.request.id, "rejected", reason); }}><XCircle className="ml-1 size-4"/>رفض</Button></div>}</div>)}</div> : <Empty title="لا توجد طلبات دفع" text="ستظهر هنا طلبات Vodafone Cash عند إرسالها من أصحاب المحلات."/>}</CardContent></Card></div>; }
function Plans({ plans, pending, onSave }: { plans: any[]; pending: boolean; onSave: (input: any) => void }) { return <div className="space-y-5"><Header title="الباقات والأسعار" text="هذه القيم هي المصدر الوحيد لحدود المتاجر والمنتجات والأسعار في التطبيق."/><div className="grid gap-4 xl:grid-cols-3">{plans.map(plan => <PlanCard key={plan.code} plan={plan} pending={pending} onSave={onSave}/>)}</div></div>; }
function PlanCard({ plan, pending, onSave }: { plan: any; pending: boolean; onSave: (input: any) => void }) { const [state, setState] = useState(plan); useEffect(() => setState(plan), [plan]); const update = (key: string, value: any) => setState((current: any) => ({ ...current, [key]: value })); return <Card className={plan.code === "pro" ? "border-primary/40" : ""}><CardHeader><CardTitle className="flex items-center justify-between"><span>{state.name}</span><span className="rounded-full bg-secondary px-2 py-1 text-[10px] uppercase text-secondary-foreground">{state.code}</span></CardTitle></CardHeader><CardContent className="space-y-4"><Field label="اسم الباقة"><Input value={state.name} onChange={e => update("name", e.target.value)}/></Field><Field label="السعر الشهري (جنيه)"><Input type="number" min="0" value={state.priceCents / 100} onChange={e => update("priceCents", Math.round(Number(e.target.value) * 100))}/></Field><div className="grid grid-cols-2 gap-3"><Field label="حد المتاجر"><Input type="number" min="1" value={state.maxShops} onChange={e => update("maxShops", Number(e.target.value))}/></Field><Field label="حد المنتجات"><Input type="number" min="1" value={state.maxProducts} onChange={e => update("maxProducts", Number(e.target.value))}/></Field></div><label className="flex items-center justify-between rounded-lg bg-secondary/70 px-3 py-2 text-xs font-bold"><span>التقارير وPDF</span><input type="checkbox" checked={Boolean(state.reportsEnabled && state.pdfExportEnabled)} onChange={e => { update("reportsEnabled", e.target.checked ? 1 : 0); update("pdfExportEnabled", e.target.checked ? 1 : 0); }}/></label><label className="flex items-center justify-between rounded-lg bg-secondary/70 px-3 py-2 text-xs font-bold"><span>الباقة متاحة للشراء</span><input type="checkbox" checked={Boolean(state.isActive)} onChange={e => update("isActive", e.target.checked ? 1 : 0)}/></label><Button className="w-full" disabled={pending} onClick={() => onSave({ ...state, reportsEnabled: Boolean(state.reportsEnabled), pdfExportEnabled: Boolean(state.pdfExportEnabled), isActive: Boolean(state.isActive) })}>حفظ التغييرات</Button></CardContent></Card>; }
function Subscriptions({ rows, pending, onChange }: { rows: any[]; pending: boolean; onChange: (shopId: number, status: "active" | "canceled" | "past_due") => void }) { return <div className="space-y-5"><Header title="إدارة الاشتراكات" text="فعّل أو أوقف حالة أي اشتراك عند الحاجة."/><Card><CardContent className="p-0">{rows.length ? <div className="divide-y">{rows.map(row => <div className="flex flex-wrap items-center gap-4 p-5" key={row.subscription.id}><div className="min-w-[190px] flex-1"><b className="block text-sm">{row.shopName}</b><p className="mt-1 text-xs text-muted-foreground">{row.ownerName ?? row.ownerEmail ?? "صاحب المحل"} · {row.subscription.plan}</p></div><span className="rounded-full bg-secondary px-3 py-1 text-xs font-bold">{statusLabel(row.subscription.status)}</span><Select value={row.subscription.status} onValueChange={(status: "active" | "canceled" | "past_due") => onChange(row.subscription.shopId, status)} disabled={pending}><SelectTrigger className="w-[150px]"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="active">فعال</SelectItem><SelectItem value="past_due">معلّق</SelectItem><SelectItem value="canceled">موقوف</SelectItem></SelectContent></Select></div>)}</div> : <Empty title="لا توجد اشتراكات" text="سيظهر أي متجر جديد فور إنشائه."/>}</CardContent></Card></div>; }
function StorefrontTemplates({ rows, pending, onChange }: { rows: any[]; pending: boolean; onChange: (shopId: number, storefrontTemplate: typeof STOREFRONT_TEMPLATES[number]["code"]) => void }) { const [previewTemplates, setPreviewTemplates] = useState<Record<number, typeof STOREFRONT_TEMPLATES[number]["code"]>>({}); return <div className="space-y-5"><Header title="قوالب المتاجر" text="اختر قالباً لمعاينته فوراً. لا يُغيّر المتجر إلا بعد الضغط على «اعتماد القالب»."/><div className="grid gap-5 xl:grid-cols-2">{rows.map(row => { const previewCode = previewTemplates[row.shopId] ?? row.storefrontTemplate; const preview = STOREFRONT_TEMPLATES.find(template => template.code === previewCode) ?? STOREFRONT_TEMPLATES[0]; const hasUnappliedPreview = previewCode !== row.storefrontTemplate; return <Card key={row.shopId} className={hasUnappliedPreview ? "border-primary/40 shadow-md shadow-primary/5" : ""}><CardHeader className="pb-3"><div className="flex items-start gap-3"><span className="mt-1 size-10 rounded-xl" style={{ backgroundColor: preview.accent }}/><div className="min-w-0"><CardTitle className="truncate text-base">{row.shopName}</CardTitle><CardDescription className="mt-1 truncate">{row.ownerName ?? row.ownerEmail ?? "صاحب المتجر"}{row.shopSlug ? ` · /store/${row.shopSlug}` : ""}</CardDescription></div></div></CardHeader><CardContent className="space-y-3"><Select value={previewCode} onValueChange={value => setPreviewTemplates(current => ({ ...current, [row.shopId]: value as typeof STOREFRONT_TEMPLATES[number]["code"] }))} disabled={pending}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{STOREFRONT_TEMPLATES.map(template => <SelectItem value={template.code} key={template.code}><span>{template.name} — {template.specialty}</span></SelectItem>)}</SelectContent></Select><StorefrontTemplatePreview shop={row} templateCode={previewCode}/><p className="rounded-xl bg-muted/60 p-3 text-xs leading-5 text-muted-foreground">{preview.description}</p><div className="flex gap-2"><Button className="flex-1" disabled={pending || !hasUnappliedPreview} onClick={() => onChange(row.shopId, previewCode)}>اعتماد القالب</Button><Button variant="outline" disabled={!hasUnappliedPreview || pending} onClick={() => setPreviewTemplates(current => { const next = { ...current }; delete next[row.shopId]; return next; })}>إلغاء المعاينة</Button></div>{hasUnappliedPreview && <p className="text-center text-[11px] font-bold text-primary">هذه معاينة مؤقتة؛ لم يُطبّق أي تغيير على المتجر.</p>}</CardContent></Card>; })}</div>{!rows.length && <Empty title="لا توجد متاجر" text="ستظهر المتاجر هنا فور إنشائها."/>}</div>; }
function Audit({ rows }: { rows: any[] }) { return <div className="space-y-5"><Header title="سجل العمليات" text="سجل تغييرات الباقات وقرارات الدفع والقوالب وحالات الاشتراكات."/><Card><CardContent className="p-0">{rows.length ? <div className="divide-y">{rows.map(row => <div key={row.log.id} className="flex items-center gap-3 p-4"><span className="grid size-9 place-items-center rounded-xl bg-secondary text-primary"><FileText className="size-4"/></span><div className="min-w-0 flex-1"><b className="block text-sm">{row.log.action}</b><p className="mt-1 truncate text-xs text-muted-foreground">{row.detail ?? row.log.detail ?? "بدون تفاصيل"}</p></div><div className="text-left"><p className="text-xs">{row.actorName ?? row.actorEmail ?? "مدير"}</p><small className="text-[10px] text-muted-foreground">{formatDate(row.log.createdAt)}</small></div></div>)}</div> : <Empty title="السجل فارغ" text="ستظهر هنا قرارات الإدارة التالية."/>}</CardContent></Card></div>; }
function Metric({ icon: Icon, label, value, tone }: { icon: any; label: string; value: string; tone: "teal" | "slate" | "gold" | "rose" }) { const colors = { teal: "bg-primary/10 text-primary", slate: "bg-slate-100 text-slate-700", gold: "bg-amber-100 text-amber-700", rose: "bg-rose-100 text-rose-700" }; return <Card><CardContent className="flex items-start justify-between p-5"><div><p className="text-xs text-muted-foreground">{label}</p><b className="mt-2 block text-xl">{value}</b></div><span className={`grid size-10 place-items-center rounded-xl ${colors[tone]}`}><Icon className="size-5"/></span></CardContent></Card>; }
function Header({ title, text }: { title: string; text: string }) { return <div><p className="text-xs font-bold tracking-wide text-primary">إدارة المنصة</p><h1 className="mt-1 text-2xl font-extrabold">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{text}</p></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <Label className="grid gap-1.5 text-xs font-bold text-muted-foreground"><span>{label}</span>{children}</Label>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="p-10 text-center"><ChevronRight className="mx-auto size-7 text-muted-foreground"/><b className="mt-3 block text-sm">{title}</b><p className="mt-2 text-xs leading-6 text-muted-foreground">{text}</p></div>; }
function statusLabel(status: string) { return status === "active" || status === "approved" ? "فعال" : status === "pending" ? "قيد المراجعة" : status === "past_due" ? "معلّق" : status === "canceled" ? "موقوف" : "مرفوض"; }
