import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ImageSourcePicker } from "@/components/ImageSourcePicker";
import { compressProductImage, type CompressedProductImage } from "@/lib/productImage";
import { trpc } from "@/lib/trpc";
import { formatMoney } from "@/lib/format";
import { ImageIcon, Loader2, Package, PackagePlus, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";

type ProductRow = { product: any; categoryName: string | null; categoryColor: string | null };
type ProductForm = { name: string; sku: string; categoryId: string; sellingPrice: string; costPrice: string; stock: string; reorder: string };

const blankForm: ProductForm = { name: "", sku: "", categoryId: "none", sellingPrice: "", costPrice: "", stock: "0", reorder: "5" };

export default function ProductWorkspace({ shopId, shop, activePlan }: { shopId: number; shop: any; activePlan: string }) {
  const [search, setSearch] = useState("");
  const products = trpc.products.list.useQuery({ shopId, search });
  const categories = trpc.categories.list.useQuery({ shopId });
  const utils = trpc.useUtils();
  const create = trpc.products.create.useMutation({ onSuccess: () => { utils.products.list.invalidate(); toast.success("تمت إضافة المنتج والصورة بنجاح"); }, onError: error => toast.error(error.message) });
  const update = trpc.products.update.useMutation({ onSuccess: () => { utils.products.list.invalidate(); toast.success("تم تحديث بيانات المنتج والصورة"); }, onError: error => toast.error(error.message) });
  const adjust = trpc.products.adjustStock.useMutation({ onSuccess: () => { utils.products.list.invalidate(); toast.success("تم تحديث المخزون"); }, onError: error => toast.error(error.message) });
  const addCategory = trpc.categories.create.useMutation({ onSuccess: () => { utils.categories.list.invalidate(); toast.success("تمت إضافة التصنيف"); }, onError: error => toast.error(error.message) });
  const createPayload = async (values: any) => create.mutateAsync({ shopId, ...values });
  const updatePayload = async (values: any) => update.mutateAsync({ shopId, ...values });

  return <div className="space-y-5"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold tracking-wide text-primary">المخزون والتصنيفات</p><h1 className="mt-1 text-2xl font-extrabold">المنتجات</h1><p className="mt-2 text-sm text-muted-foreground">الخطة الحالية: {activePlan === "free" ? "مجانية" : activePlan === "basic" ? "أساسية" : "احترافية"}</p></div><div className="flex flex-wrap gap-2"><CategoryDialog onSubmit={value => addCategory.mutate({ shopId, ...value })}/><ProductFormDialog categories={categories.data ?? []} onSubmit={createPayload}/></div></header><div className="flex flex-wrap items-center gap-3"><div className="relative min-w-[220px] flex-1"><Search className="absolute right-3 top-3 size-4 text-muted-foreground"/><Input className="pr-9" value={search} onChange={event => setSearch(event.target.value)} placeholder="ابحث باسم المنتج أو SKU"/></div><span className="rounded-lg bg-secondary px-3 py-2 text-xs font-bold text-secondary-foreground">{products.data?.length ?? 0} منتج</span></div>{products.isLoading ? <div className="grid min-h-56 place-items-center"><Loader2 className="animate-spin text-primary"/></div> : products.data?.length ? <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{products.data.map((row: ProductRow) => <ProductCard key={row.product.id} row={row} currency={shop.currency} categories={categories.data ?? []} onUpdate={updatePayload} onAdjust={delta => adjust.mutate({ shopId, productId: row.product.id, quantityDelta: delta })}/>)}</div> : <Card><CardContent className="p-10 text-center"><PackagePlus className="mx-auto size-10 text-primary"/><h2 className="mt-4 font-bold">لا توجد منتجات حتى الآن</h2><p className="mt-2 text-sm text-muted-foreground">أضف أول منتج مع صورته وسعره وحد إعادة الطلب.</p></CardContent></Card>}</div>;
}

function ProductCard({ row, currency, categories, onUpdate, onAdjust }: { row: ProductRow; currency: string; categories: any[]; onUpdate: (values: any) => Promise<unknown>; onAdjust: (delta: number) => void }) { const product = row.product; const isLow = product.quantityInStock <= product.reorderPoint; return <Card className="overflow-hidden border-border/70 transition hover:-translate-y-0.5 hover:shadow-lg hover:shadow-primary/5"><CardContent className="p-0"><div className="flex gap-4 p-4"><ProductImage src={product.productImage} name={product.name} className="size-20 shrink-0 rounded-2xl"/><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><h2 className="truncate font-bold">{product.name}</h2><p className="mt-1 text-xs text-muted-foreground">{row.categoryName ?? "بدون تصنيف"}{product.sku ? ` · ${product.sku}` : ""}</p></div><ProductDetailsDialog row={row} currency={currency}/></div><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl bg-secondary/70 px-3 py-2"><p className="text-[10px] text-muted-foreground">السعر</p><b className="mt-1 block text-sm">{formatMoney(product.sellingPriceCents, currency)}</b></div><div className={`rounded-xl px-3 py-2 ${isLow ? "bg-amber-50 text-amber-800" : "bg-secondary/70"}`}><p className="text-[10px] text-muted-foreground">الكمية</p><b className="mt-1 block text-sm">{product.quantityInStock} قطعة</b></div></div></div></div><div className="flex flex-wrap gap-2 border-t bg-muted/20 p-3"><ProductFormDialog product={product} categories={categories} onSubmit={onUpdate} trigger={<Button size="sm" variant="outline"><Pencil className="ml-1 size-3.5"/>تعديل</Button>}/><Button variant="outline" size="sm" onClick={() => { const value = window.prompt("أدخل كمية الإضافة أو الخصم، مثال: 5 أو -2"); const delta = Number(value); if (Number.isInteger(delta) && delta) onAdjust(delta); }}>المخزون</Button></div></CardContent></Card>; }

function ProductFormDialog({ categories, onSubmit, product, trigger }: { categories: any[]; onSubmit: (values: any) => Promise<unknown>; product?: any; trigger?: React.ReactNode }) {
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState<ProductForm>(blankForm);
  const [image, setImage] = useState<CompressedProductImage | null>(null);
  const [removeImage, setRemoveImage] = useState(false);
  const [compressing, setCompressing] = useState(false);
  const [saving, setSaving] = useState(false);
  useEffect(() => { if (open) { setForm(product ? { name: product.name, sku: product.sku ?? "", categoryId: product.categoryId ? String(product.categoryId) : "none", sellingPrice: String(product.sellingPriceCents / 100), costPrice: String(product.costPriceCents / 100), stock: String(product.quantityInStock), reorder: String(product.reorderPoint) } : blankForm); setImage(null); setRemoveImage(false); } }, [open, product]);
  const handleImage = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; try { setCompressing(true); const compressed = await compressProductImage(file); setImage(compressed); setRemoveImage(false); toast.success("تم ضغط الصورة وتجهيز المعاينة"); } catch { toast.error("استخدم صورة JPG أو PNG أو WEBP لا تزيد عن 10 ميغابايت."); } finally { setCompressing(false); } };
  const submit = async (event: FormEvent) => { event.preventDefault(); try { setSaving(true); await onSubmit({ name: form.name, sku: form.sku || undefined, categoryId: form.categoryId === "none" ? null : Number(form.categoryId), sellingPriceCents: Math.round(Number(form.sellingPrice) * 100), costPriceCents: Math.round(Number(form.costPrice || 0) * 100), quantityInStock: Number(form.stock), reorderPoint: Number(form.reorder), productImageBase64: image?.dataUrl, productImageContentType: image?.contentType, ...(product ? { productId: product.id, removeProductImage: removeImage } : {}) }); setOpen(false); } finally { setSaving(false); } };
  const preview = image?.previewUrl ?? (!removeImage ? product?.productImage : null);
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild>{trigger ?? <Button><Plus className="ml-2 size-4"/>إضافة منتج</Button>}</DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{product ? "تعديل المنتج" : "إضافة منتج"}</DialogTitle><DialogDescription>اختر صورة من الاستوديو أو التقطها بالكاميرا. تُضغط تلقائياً قبل الحفظ للحفاظ على سرعة التطبيق.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4"><Field label="صورة المنتج"><div className="flex flex-wrap items-center gap-3"><ProductImage src={preview} name={form.name || "منتج"} className="size-20 rounded-2xl"/><div className="min-w-[180px] flex-1"><ImageSourcePicker onSelect={handleImage} disabled={compressing || saving}/><p className="mt-2 text-[11px] leading-5 text-muted-foreground">JPG أو PNG أو WEBP، حتى 10 ميغابايت. تتحول تلقائياً إلى WebP بعرض أقصى 1280px.</p>{preview && <button type="button" className="mt-2 inline-flex items-center text-xs font-bold text-destructive" onClick={() => { setImage(null); setRemoveImage(true); }}><Trash2 className="ml-1 size-3.5"/>إزالة الصورة</button>}</div></div>{compressing && <p className="flex items-center gap-2 text-xs text-primary"><Loader2 className="size-3.5 animate-spin"/>يجري ضغط الصورة…</p>}</Field><Field label="اسم المنتج"><Input value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} required/></Field><div className="grid grid-cols-2 gap-3"><Field label="سعر البيع"><Input type="number" min="0" step="0.01" value={form.sellingPrice} onChange={event => setForm({ ...form, sellingPrice: event.target.value })} required/></Field><Field label="سعر التكلفة"><Input type="number" min="0" step="0.01" value={form.costPrice} onChange={event => setForm({ ...form, costPrice: event.target.value })}/></Field></div><div className="grid grid-cols-2 gap-3"><Field label="الكمية الحالية"><Input type="number" min="0" value={form.stock} onChange={event => setForm({ ...form, stock: event.target.value })} required/></Field><Field label="حد إعادة الطلب"><Input type="number" min="0" value={form.reorder} onChange={event => setForm({ ...form, reorder: event.target.value })} required/></Field></div><Field label="التصنيف"><Select value={form.categoryId} onValueChange={categoryId => setForm({ ...form, categoryId })}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">بدون تصنيف</SelectItem>{categories.map(category => <SelectItem key={category.id} value={String(category.id)}>{category.name}</SelectItem>)}</SelectContent></Select></Field><Field label="رمز المنتج (اختياري)"><Input value={form.sku} onChange={event => setForm({ ...form, sku: event.target.value })}/></Field><Button type="submit" className="w-full" disabled={saving || compressing}>{saving && <Loader2 className="ml-2 size-4 animate-spin"/>}{product ? "حفظ التغييرات" : "إضافة المنتج"}</Button></form></DialogContent></Dialog>;
}

function ProductDetailsDialog({ row, currency }: { row: ProductRow; currency: string }) { return <Dialog><DialogTrigger asChild><Button size="icon" variant="ghost" className="size-8" aria-label="عرض تفاصيل المنتج"><Package className="size-4"/></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>تفاصيل المنتج</DialogTitle></DialogHeader><div className="space-y-5"><ProductImage src={row.product.productImage} name={row.product.name} className="h-52 w-full rounded-2xl"/><div><h3 className="text-lg font-extrabold">{row.product.name}</h3><p className="mt-1 text-sm text-muted-foreground">{row.categoryName ?? "بدون تصنيف"}</p></div><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-secondary p-3"><p className="text-xs text-muted-foreground">سعر البيع</p><b className="mt-1 block">{formatMoney(row.product.sellingPriceCents, currency)}</b></div><div className="rounded-xl bg-secondary p-3"><p className="text-xs text-muted-foreground">الكمية المتاحة</p><b className="mt-1 block">{row.product.quantityInStock} قطعة</b></div></div></div></DialogContent></Dialog> }
function CategoryDialog({ onSubmit }: { onSubmit: (value: { name: string; color: string }) => void }) { const [open, setOpen] = useState(false); const [name, setName] = useState(""); return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline"><Plus className="ml-1 size-4"/>تصنيف</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>تصنيف جديد</DialogTitle></DialogHeader><form className="space-y-4" onSubmit={event => { event.preventDefault(); onSubmit({ name, color: "#0f766e" }); setOpen(false); }}><Field label="اسم التصنيف"><Input value={name} onChange={event => setName(event.target.value)} required/></Field><Button className="w-full" type="submit">حفظ التصنيف</Button></form></DialogContent></Dialog> }
function ProductImage({ src, name, className }: { src?: string | null; name: string; className: string }) { const [failed, setFailed] = useState(false); useEffect(() => setFailed(false), [src]); if (!src || failed) return <div className={`grid place-items-center bg-gradient-to-br from-primary/15 to-secondary text-primary ${className}`}><span className="text-center"><ImageIcon className="mx-auto size-6"/><small className="mt-1 block text-[10px]">بدون صورة</small></span></div>; return <img src={src} alt={`صورة ${name}`} className={`object-cover ${className}`} onError={() => setFailed(true)}/> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <Label className="grid gap-1.5 text-sm"><span>{label}</span>{children}</Label> }
